### ISSUE TITLE
Workflow docs - word docs w/o a pdf rendition attached as WF docs break approval route

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#150]
To reproduce:
1. search for and select a word doc that is a draft controlled document
2. group actions > create wizard form
3. select Simple CR in createwizardform.js
4. fill out the form and submit
5. start the approval route
6. complete the approval route <-- signature page will fail to generate since the wf doc is a word doc with no pdf rendition.

To fix this, shouldn't we add a condition bean to create wizard form as a group action where the doc must either be a pdf or have a pdf rendition?

here's the currently configured conditions for fromWfDocs action:

```xml
<property name="requiredConditionEvaluatorList">
	<list>
		<value>condition-isawizardcontributor-conditionevaluator</value>
		<value>condition-isdraftlifecyclestate-conditionevaluator</value>
		<value>condition-isworkflowdocnotalreadyattached-conditionevaluator</value>
	</list>
</property>
```

**Comment by gsteimer** [comment]
Yes - both the form and the attached documents must have PDF renditions to start the route in your case.  But, it gets tricky, because it really only needs a PDF rendition if one of the tripped roles requires a signature on workflow docs.  This is the reason we haven't done this yet.  It's not as simple as just blanket saying all workflow docs must have a PDF rendition.  You can have all the following valid routing scenarios:

1. Form with no docs attached, role tripped with signatures required 
1. Form with docs attached, role tripped with signatures required (PDFs of docs must be present - this is your case)
1. Form with docs attached, role tripped with *signatures on workflow docs not required* (PDFs of docs aren't required)
1. Form with docs attached, role *not tripped* with signatures required (PDFs of docs aren't required)

It's those last two cases that make this more difficult than at first glance.  Before saying that PDFs of docs are required, you first have to look at the tripped roles, and then also look to see whether or not signatures are enabled on the role.

Seeing that almost all clients auto-render to PDF, this is rarely, if ever an issue.  I'm going to move this to Upon Client Request...

**Comment by gsteimer** [comment]
Closing this, since we fixed this issue in HPI: https://github.com/tsgrp/hpi/issues/593.  If you do not have a PDF rendition and your role is configured for eSig, HPI will not allow you to complete your task.
