### ISSUE TITLE
Leading pages are not inserted to page flow in a consistent order and are sometimes removed incorrectly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#164]
See the screencam below.  Forms with complicated leading actions seem to not be working well at all:

**TS Leading Actions on edge1**
![leading-order-wrong](https://cloud.githubusercontent.com/assets/1377228/5821351/032d4842-a091-11e4-9f08-9d78701c7971.gif)

Some issues I see:

- [ ] The pages are not in the correct and consistent order (see rules below)
- [ ] pg2 gets removed from the page flow incorrectly - especially when question 1 and question 2 both lead to pg2.

Be sure to meet with me before tackling this issue.

**Comment by gsteimer** [comment]
I just added this wiki page to help describe how leading actions should be inserted into the page flow:

https://github.com/tsgrp/ActiveWizard/wiki/Leading-Actions

Also, I'm fine with closing this issue if #163 is still outstanding.  We can track that feature separately.

**Comment by gsteimer** [comment]
FYI - @dgrumieaux @mikeblum - does your current client have any leading scenarios like these.  AW clients historically have been very picky about the order that pages show up.  If the HTML5 form deviates from how Flex ordered the pages, we will most likely need to tackle this issue.

**Comment by mikeblum** [comment]
#163 is supported as far as i know.

**Comment by gsteimer** [comment]
@mikeblum - Something must have happened then, because it's definitely not working.  See https://github.com/tsgrp/ActiveWizard/issues/163#issuecomment-70692896

**Comment by mikeblum** [comment]
Confirmed the ordering bug is that the order changes based on the order the questions are answered.

As a starting point for this fix, lets make ordering consistent and then tackle or defer the case of two pages all leading to the same third page.

**Comment by mikeblum** [comment]
Revision: 11618
Author: mblum
Date: 2015-01-28 08:24:48.195124
WIZARD FLOWPATH AND SUPPORTING DOCS: resolved an issue with flowpath where pages we're being inserted in the oder the questions were answered rather then the configured question order. Updated supporting docs contract to be in line with Bulk Uploa now returning and array of mapped object names with their object ids. Nore: this will break export forms. *\* OC Update Required **

M   /trunk/code/app/modules/wizard/models/flowpath.js
M   /trunk/code/app/templates/wizard/sortable.html
M   /trunk/code/app/modules/wizard/models/question.js
M   /trunk/code/app/modules/wizard/services/pagesetinstanceprovider.js
M   /trunk/code/app/modules/wizard/views/flowpathview.js
M   /trunk/code/app
M   /trunk/code
A   /trunk/code/test/tests/modules/wizard/wizard/actioncacheSpec.js
M   /trunk/code/test/tests
M   /trunk/code/app/modules/wizard/models/pagesetinstance.js
M   /trunk/code/test/tests/modules/wizard/wizard/flowpathSpec.js
M   /trunk/code/app/modules/wizard/views/controltypes.js
M   /trunk/code/test/tests/modules/wizard/wizard/questionSpec.js
A   /trunk/code/app/modules/wizard/models/actioncache.js

Revision: 10622
Author: mblum
Date: 2015-01-27 09:36:27.179499
WIZARD SUPPORTING DOCS: updated contract we have with bulk upload to now use the map of keyys (object names) and values (objectIds). Tested with add doc and remove supporting doc.
FLOWPATH:  added recursive parser to find each valid flowpath node since we now persist the full flowpath with all possible pages (Check Export Forms action after this merge).

M   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/action/executer/FinishAndSubmitPSIActionExecutor.java
M   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/core/IWizard2.java
M   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/action/executer/SaveWizardFormActionExecuter.java
M   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/core/Wizard2Impl.java

**Comment by mikeblum** [comment]
note: check export forms after the flowpath updates.
