### ISSUE TITLE
After editing form in a review route, the complete review route action disappears

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#168]
After editing a form that is in a review route (on edge1), I can no longer see the Complete Review task action:

![image](https://cloud.githubusercontent.com/assets/1377228/5862422/5e22cb58-a237-11e4-8cbf-206b5e25d8a8.png)

@dgrumieaux @mikeblum @benallenallen - will this be an issue for our current client?

**Comment by gsteimer** [comment]
I just tried deleting the latest version in dqMan, and then the complete wizard review action appeared again.  So it's definitely getting confused when something on the workflow is versioned.

I'm guessing this is also related to #86.  When I wrote that issue, I thought it was Alfresco specific, but apparently not.

**Comment by dgrumieaux** [comment]
Fixed in SVN rev 10863.

**Comment by gsteimer** [comment]
@dgrumieaux - this is not working on edge1:

![image](https://cloud.githubusercontent.com/assets/1377228/6249082/6ecb0222-b74a-11e4-9d4c-de0dd08c8bd2.png)

And my complete task link goes away...

![image](https://cloud.githubusercontent.com/assets/1377228/6249094/7e492cba-b74a-11e4-8a7d-46a055a0f204.png)

**Comment by dgrumieaux** [comment]
This bug was due to the workflow definition failing to save due to wizard_contributors not having the extended Documentum permission CHANGE_PERMIT. It was not clear why this error was happening, but adding the CHANGE_PERMIT permission to the wizard_wizard_acl was deemed an acceptable solution. Commit and fixed in HPI rev 11761.
