### ISSUE TITLE
Cannot trigger leading action from Typeahead selectbox

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#189]
See the Equipment Request form on edge1.  If you try to lead from a selectbox typeahead, the leading actions do not appear.

After fixing this, we should add a test case for this to the TS Leading Actions form.

In the screenshot below - the status should show that the form is leading to the Mobile Device Request page, but it's not:
![image](https://cloud.githubusercontent.com/assets/1377228/6376926/96defd44-bce6-11e4-86e2-100bd17cf188.png)

FYI @mikeblum

**Comment by gsteimer** [comment]
@mikeblum - thanks for the quick turnaround..  I tested this on edge1 and it seems to be working.  Can you comment with your commit rev number and close this issue?

**Comment by mikeblum** [comment]
## Crux of the problem was trying to compare a string and a JS object.

Revision: 11801
Author: mblum
Date: 2015-02-25 12:27:28.142558
WIZARD LEADING ACTIONS:updated unit tests to better capture the typeahead cases with leading actions.

M   /trunk/code/test/tests/modules/wizard/wizard/questionSpec.js

Revision: 11799
Author: mblum
Date: 2015-02-25 12:06:51.205058
WIZARD LEADING ACTIONS FROM TYPEAHEAD & TOSSACROSS: fix where if a leading action's answer was an object the comparison failed. test pending.

M   /trunk/code/app/modules/wizard/models/question.js
