### ISSUE TITLE
UsersInGroupsQuery returning all users

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#240]
If you pay attention to the users being returned in Simple CR's 'Approvers' question, you'll notice that all repository users are included in the list, not just users in the `wizard_contributors` group.  It looks like this is because Active Form is not passing through the WebService URL (which in this case is the group name) to the bean properly.  Line 36 in `UsersInGroupsQuery.java` returns empty string each time:

`String groupNamesDelimited = queryAction.getWebserviceUrl();`

This causes the following SQL to eventually be run:

``` sql
SELECT u.r_object_id, u.user_login_name, u.user_name, u.user_address FROM dm_user u WHERE r_is_group = FALSE  ORDER BY u.user_name asc
```

If you debug the same code, but run it from the 'Test Query' feature in the AW Admin, you get the correct query (and results):

``` sql
SELECT u.r_object_id, u.user_login_name, u.user_name, u.user_address FROM dm_user u WHERE r_is_group = FALSE  AND  u.user_name IN (SELECT i_all_users_names FROM dm_group WHERE group_name = 'wizard_contributors') ORDER BY u.user_name asc
```

Side note, could this be related to #237 ?

**Comment by grahamsinger** [comment]
Fixed, waiting for OC access and CR.

**Comment by grahamsinger** [comment]
Fixed with OC rev11975

For querys with no substitutions, the `webServiceUrlValue` was not being set even though the `webServiceUrl` had the right value.

Made a change so that is there isn't a `webServiceUrlValue` (meaning that there weren't any substitutions), we fall back on the `webServiceUrl` that does contain the value we want.

CR: George
