### ISSUE TITLE
Answer Justifications - Incorrectly asks for justifications

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#241]
In `TS Answer Justifications`, answers that do not require justifications are still asking for justification text. This seems to only be the case for dropdowns and working on checkbox and radio.

![image](https://cloud.githubusercontent.com/assets/1377228/8577020/8b3dca54-256b-11e5-97cb-dbf7fc52cc57.png)

**Comment by grahamsinger** [comment]
Fixed. Creating spec file for abstractcontrol.js with unit test/s.

**Comment by grahamsinger** [comment]
Fixed with revision 12680.

When a justification view was supposed to be removed/not show up, we were removing the view, but then re-rendering that view, causing the justification view to always be present.  I added in an if/else so that it either removes the view or renders the view, not both.

Created abstractcontrolSpec.js to test.

CR: MB
