### ISSUE TITLE
Cannot add justification for radio button question

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#244]
After the updates to #241, I cannot add justification text for a radio button question in `TS Answer Justifications`.  See the screencam below.  When I click in the justification box, it quickly loses focus.  I can get a keystoke or two in if I try really quickly.

![justify-radio-fail](https://cloud.githubusercontent.com/assets/1377228/8674298/a60275f6-2a02-11e5-8f6a-88bf7b0f6aeb.gif)

**Comment by grahamsinger** [comment]
Fixed with rev12685

When clicking/typing in the justification box, the `check()` function was run to see if there was a change in value of the radio button.  This was causing a new justification view to be rendered, which would clear out the input and cause a loss of focus.  We don't need to "check" when the justification box is clicked or typed in, so we aren't anymore.

CR: MB
