### ISSUE TITLE
Default Radio Button Values Are Broken

### ISSUE THREAD

**Issue by zkeller** [tsgrp/ActiveWizard#245]
See gif below. If using a default value for radio buttons, the default value doesn't register for form validity.

![defaultradiobutton](https://cloud.githubusercontent.com/assets/4852355/8679404/222aa85c-2a20-11e5-9820-8ec8412d6031.gif)

**Comment by grahamsinger** [comment]
Fixed with rev12689.

Along with this issue, I also found out that default check boxes also had some issues with them.  

For the radio buttons, the default value was (as shown above) being correctly shown as pressed, however the actual value on the field was never set, causing the issue above.  

For checkboxes, the issue was twofold.  First, the defaults would not be put in an array, which was what the control was expecting... This caused the `_.each` to not work as expected and didn't show the defaulted check boxes as checked.  Secondly, we needed to account for the fact that for checkboxes, there can be more than one value selected to be defaulted.  Accounted for this by putting the values in an array so that the control can process them correctly.

Unit tested.

CR: MB
