### ISSUE TITLE
Repeating Table - Delete item after reorder deletes wrong row

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#251]
See the screencam below.  Deleting items in the table seems to work fine, until I reorder.  After the reorder, clicking delete on the row removes the wrong row from the table:

![repeating-table-delete](https://cloud.githubusercontent.com/assets/1377228/9071672/2c9c7ce6-3abc-11e5-9f20-6d960a4befdf.gif)

**Comment by grahamsinger** [comment]
Fixed with revision 12834

We were just swapping the rows before when we rearranged instead of having the rows adjust as expected and indicated by jQuery sortable.  Also, we were never reordering the `questionGroups[]` so when we went to delete after rearranging the rows, it would be deleting the wrong row. So now, we ensure that both the individual question models as well as the question groups are in the right order so both rearranging, deleting.  Lastly, previously we were just getting the last element in the `questionGroups[]` assuming that it would have the highest row number `..._rX`.  As stated before, this wasn't as issue because we never actually reorganized that array to match what was going on in the table.  I changed the `getLastQuestionGroup()` to make sure to find the highest row number because adding rows would fail otherwise.

Unit tested.

CR: Mike B
