### ISSUE TITLE
Changing Leading Action Causes All Pages to Disappear

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#253]
See the screencam below.  If I change a leading action, the pages change accordingly.  However, if I actually go to the page, then come back to the original page and change to remove the page out of the flowpath, all pages in the form disappear.

![leading-summary-disappear](https://cloud.githubusercontent.com/assets/1377228/9343076/5f10c646-45c5-11e5-9682-f7b8a5f079eb.gif)

A few notes:
- This is working fine using the TS Leading Actions page set
- This form has four leading answers.  Two of them lead to pages that have tables.
- TS Leading Actions doesn't have any tables, so perhaps the tables being in the form are contributing to the problem?  (The `Server` and `Other` answers in the Equipment Request form do not lead to pages with tables)
  - If i lead to a page without tables and then change to page without tables, **it works**.
  - If I lead to a page without tables and then change to page with tables, **it fails**.
  - If I lead to a page with tables and then change to page without tables, **it works**.

@mikeblum

**Comment by gsteimer** [comment]
For the steps to reproduce above, I just got it to happen without actually going to to page.   I just had to change the leading action to a page that had tables and I got it to happen...

**Comment by mikeblum** [comment]
r12891 | mblum | 2015-08-18 17:39:08 -0500 (Tue, 18 Aug 2015) | 1 line

rolled back wizard flowpath code that attempted to turn off a parent page for unlimited chains of non-required questions. Equipment Request OK

Root cause was our flowpath algorithm intelligently (not so much) trying to turn off parent pages when their children are no longer lead to. Creating a new issue to support unlimited chained pages...
