### ISSUE TITLE
Forms cannot be created in IE

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/ActiveWizard#259]
Trying to create a form in IE creates the URL: 

`http://burling:9000/hpi/activeform/Simple%20CR/activeform/Simple%20CR/new/0` 

when it should be: 

`http://burling:9000/activeform/Simple%20CR/new/0`

**Comment by gsteimer** [comment]
Hmm... the 'incorrect' URL is actually correct for edge1/2, right?  Since the `/hpi` context is created from the hpi.war.

However, when I try to create a form on edge2 using Simple CR - I just see this:

![image](https://cloud.githubusercontent.com/assets/1377228/9524809/821953f0-4ca6-11e5-9844-89f57aab7c1f.png)

**Comment by grahamsinger** [comment]
Fixed. Awaiting CR

**Comment by grahamsinger** [comment]
Fixed with rev12958

Used better practices when setting the url (i.e. `window.location.protocol + "//" + window.location.host +...`)

Tested creating and editing form in IE11, IE10, IE9, FF, Chrome

CR: DG
