### ISSUE TITLE
Manage Security is broken

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#264]
Can't edit lifecycles for the Wizard form states:

![selection_083](https://cloud.githubusercontent.com/assets/3905463/10258741/58857efa-6926-11e5-8b46-e91544044cc3.png)

**Comment by gsteimer** [comment]
I think this looks worse than it is. I'm pretty sure the AW admin had a small issue where the admin thinks the configured ACLs aren't there, but that's just because it's indirectly looking for an ACL called "Lifecycle Default", which obviously doesn't exist. 

If you save on this screen, does it go back to normal?

**Comment by benallenallen** [comment]
I may have lied to you @mikeblum 

I think that "error" always shows up until you actually select a different acl.

**Comment by mikeblum** [comment]
Save is disabled and I can't click any dropdowns to change the lifecycle.

**Comment by gsteimer** [comment]
I'm pretty sure you have to check out the page set first

**Comment by mikeblum** [comment]
@gsteimer you're correct, need to checkout first.  Closing...
